export const routes = {
  HOMESCREEN: 'HOMESCREEN',
  NOTIFICATIONSCREEN: 'NOTIFICATIONSCREEN',
  SEARCHSCREEN: 'SEARCHSCREEN',
  PROFILESCREEN: 'PROFILESCREEN',
  BOTTOMTABBAR: 'BOTTOMTABBAR',
  LISTCATEGORYFILTER: 'LISTCATEGORYFILTER',
  PRODUCTDETAIL: 'PRODUCTDETAIL',
  CARTSCREENS: 'CARTSCREENS',
  PAYMENTSCREENS: 'PAYMENTSCREENS',
  SUCCESSSCREENS: 'SUCCESSSCREENS',
};
